-- MySQL Script generated by MySQL Workbench
-- Fri May  2 14:39:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema commuconnect
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `commuconnect` ;

-- -----------------------------------------------------
-- Schema commuconnect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `commuconnect` DEFAULT CHARACTER SET utf8 ;
USE `commuconnect` ;

-- -----------------------------------------------------
-- Table `commuconnect`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(60) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_administrador`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `commuconnect`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Ciudad` (
  `id_ciudad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Distrito` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Distrito` (
  `id_distrito` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_distrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `id_ciudad` INT NULL,
  `id_distrito` INT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `id_ciudad_idx` (`id_ciudad` ASC) VISIBLE,
  INDEX `id_distrito_idx` (`id_distrito` ASC) VISIBLE,
  CONSTRAINT `id_ciudad`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `commuconnect`.`Ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_distrito`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `commuconnect`.`Distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `tipo_documento` ENUM('DNI', 'CARNET DE EXTRANJERIA') NOT NULL,
  `num_doc` VARCHAR(45) NOT NULL,
  `direccion_detallada` VARCHAR(350) NULL,
  `fecha_nac` DATETIME NULL,
  `genero` VARCHAR(45) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `num_doc_UNIQUE` (`num_doc` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_direccion_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cli`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `commuconnect`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_cli`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `commuconnect`.`Direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Tipo_Documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Tipo_Documento` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Tipo_Documento` (
  `id_tipo_documento` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Comunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Comunidad` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Comunidad` (
  `id_comunidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(350) NULL,
  `imagen` LONGBLOB NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_comunidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Servicios` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripccion` VARCHAR(100) NULL,
  `imagen` LONGBLOB NULL,
  `modalidad` ENUM('Virtual', 'Presencial') NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_servicio`));


-- -----------------------------------------------------
-- Table `commuconnect`.`Local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Local` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `id_direccion` INT NULL,
  `id_servicio` INT NULL,
  `direccion_detallada` VARCHAR(350) NULL,
  `responsable` VARCHAR(45) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_local`),
  INDEX `id_servicio_idx` (`id_servicio` ASC) VISIBLE,
  INDEX `id_direccion_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_l`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `commuconnect`.`Servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_l`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `commuconnect`.`Direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`ComunidadxServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`ComunidadxServicio` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`ComunidadxServicio` (
  `id_comunidad` INT NOT NULL,
  `id_servicio` INT NOT NULL,
  PRIMARY KEY (`id_comunidad`, `id_servicio`),
  INDEX `id_servicio_idx` (`id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_comunidad_CS`
    FOREIGN KEY (`id_comunidad`)
    REFERENCES `commuconnect`.`Comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_CS`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `commuconnect`.`Servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`ClientexComunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`ClientexComunidad` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`ClientexComunidad` (
  `id_cliente` INT NOT NULL,
  `id_comunidad` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_comunidad`),
  INDEX `id_comunidad_idx` (`id_comunidad` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_CC`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `commuconnect`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comunidad_CC`
    FOREIGN KEY (`id_comunidad`)
    REFERENCES `commuconnect`.`Comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commuconnect`.`Sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Sesion` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Sesion` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `id_servicio` INT NULL,
  `descripccion` VARCHAR(100) NOT NULL,
  `inicio` DATETIME NULL,
  `fin` DATETIME NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_sesion`),
  INDEX `id_servicio_idx` (`id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_S`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `commuconnect`.`Servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Sesion_Presencial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Sesion_Presencial` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Sesion_Presencial` (
  `id_sesion_presencial` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` INT NULL,
  `id_local` INT NULL,
  `capacidad` INT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_sesion_presencial`),
  INDEX `id_sesion_idx` (`id_sesion` ASC) VISIBLE,
  INDEX `id_local_idx` (`id_local` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_SP`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `commuconnect`.`Sesion` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_SP`
    FOREIGN KEY (`id_local`)
    REFERENCES `commuconnect`.`Local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Profesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Profesional` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Profesional` (
  `id_profesional` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `formulario` BLOB NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_profesional`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_PRO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `commuconnect`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Sesion_Virtual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Sesion_Virtual` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Sesion_Virtual` (
  `id_sesion_virtual` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` INT NULL,
  `id_profesional` INT NULL,
  `doc_asociado` BLOB NULL,
  `descripcion?` VARCHAR(300) NULL,
  `URL` VARCHAR(500) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_sesion_virtual`),
  INDEX `id_sesion_idx` (`id_sesion` ASC) VISIBLE,
  INDEX `id_profesional_idx` (`id_profesional` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_SV`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `commuconnect`.`Sesion` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesional_SV`
    FOREIGN KEY (`id_profesional`)
    REFERENCES `commuconnect`.`Profesional` (`id_profesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` INT NULL,
  `id_cliente` INT NULL,
  `fecha_reservada` DATETIME NULL,
  `estado_reserva` VARCHAR(45) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_sesion_idx` (`id_sesion` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_R`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `commuconnect`.`Sesion` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_R`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `commuconnect`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Plan` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Plan` (
  `id_plan` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(300) NULL,
  `topes` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_plan`));


-- -----------------------------------------------------
-- Table `commuconnect`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Pago` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NULL,
  `fecha_pago` DATETIME NULL,
  `metodo_pago` ENUM('Tarjeta', 'Efectivo') NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_pago`));


-- -----------------------------------------------------
-- Table `commuconnect`.`Inscripción`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Inscripción` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Inscripción` (
  `id_inscripcion` INT NOT NULL AUTO_INCREMENT,
  `id_plan` INT NULL,
  `id_comunidad` INT NULL,
  `id_cliente` INT NULL,
  `id_pago` INT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_inscripcion`),
  INDEX `id_comunidad_idx` (`id_comunidad` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_plan_idx` (`id_plan` ASC) VISIBLE,
  INDEX `id_pago_idx` (`id_pago` ASC) VISIBLE,
  CONSTRAINT `fk_comunidad_I`
    FOREIGN KEY (`id_comunidad`)
    REFERENCES `commuconnect`.`Comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_I`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `commuconnect`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_I`
    FOREIGN KEY (`id_plan`)
    REFERENCES `commuconnect`.`Plan` (`id_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_I`
    FOREIGN KEY (`id_pago`)
    REFERENCES `commuconnect`.`Pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Detalle_Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Detalle_Inscripcion` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Detalle_Inscripcion` (
  `id_registros_inscipcion` INT NOT NULL AUTO_INCREMENT,
  `id_inscripcion` INT NULL,
  `fecha_registro` DATETIME NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `topes_disponibles` INT NULL,
  `topes_consumidos` INT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_registros_inscipcion`),
  INDEX `id_inscripcion_idx` (`id_inscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcion_DI`
    FOREIGN KEY (`id_inscripcion`)
    REFERENCES `commuconnect`.`Inscripción` (`id_inscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `commuconnect`.`Suspension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commuconnect`.`Suspension` ;

CREATE TABLE IF NOT EXISTS `commuconnect`.`Suspension` (
  `id_suspension` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL,
  `id_inscripcion` INT NULL,
  `motivo` VARCHAR(300) NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `archivo` LONGBLOB NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_por` VARCHAR(50) NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  `modificado_por` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_suspension`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_inscripcion_idx` (`id_inscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_Sus`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `commuconnect`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_Sus`
    FOREIGN KEY (`id_inscripcion`)
    REFERENCES `commuconnect`.`Inscripción` (`id_inscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
